### ISSUE TITLE
有个小问题请教下~

### ISSUE THREAD

**Issue by xuhongv** [AngelLiang/ESP8266-Demos#1]
我对8266的SPI操作不熟悉，请问您这个demo里面的TM7705是软件模拟spi么？

**Comment by AngelLiang** [comment]
是的，spi_app里面的TM7705是软件模拟spi，也就是soft_spi。当然，hard_spi就是指硬件SPI。

**Comment by xuhongv** [comment]
@AngelLiang 嗯嗯！可以看下你的TM7705的连接图么？我这边需求SPI驱动一个nRF24L的 ，发现走硬件SPI不行，想参考下您这个接法，不知道可以不可以呢?

**Comment by AngelLiang** [comment]
关于 soft spi 引脚可参考`app/include/user_spi.h`下的宏定义。另外spi_app的README已经更新，可以参考一下。

```C
// app/include/user_spi.h

/********************************************************************/
// 可能需要修改下面的宏定义

//#define HARD_SPI
#define SOFT_SPI

#define MISO_PIN 12
#define MOSI_PIN 13
#define SCK_PIN  14
#define CS_PIN	   15
```

**Comment by xuhongv** [comment]
非常给力亲。在网上开源代码的朋友都是很好说话的。哈哈

**Comment by xuhongv** [comment]
我还有个小问题：
 - 请问使用smartConfig配网成功后，8266可以回调自定义数据返回给App么？
  - 我发现现在APP只能获取到8266的mac地址和IP地址... 看不到代码，因为是以库文件存在的...

**Comment by AngelLiang** [comment]
你这个问题我也考虑过，目前还没有很好的解决方案：

1. 有的人是在ssid或password弄一个分隔符，分隔符前面是Wi-Fi信息，后面就放自己的信息了；
2. 还有的是让用户多次触发SmartConfig（比如重启ESP8266），然后在APP端像配网一样传递数据。
3. 目前我觉得比较好的方案是，ESP8266配网成功后，再通过TCP或UDP传输数据到APP端即可，不经过SmartConfig了。

**Comment by xuhongv** [comment]
- 第三点我做8266与APP端配网成功后走UDP，成功了！就是有没有更好的办法，我不想再走一遍TCP或UDP；这是我封装的Android配网8266库支持自定义回调：https://github.com/xuhongv/XSmartConfig

- 至于第一点我还是不懂您的意思。当前需要的是自定义回调给APP，这个WI-Fi信息回调也看不到的源代码的。
